name = "DeepONet"
uuid = "f5d89359-17ff-402f-9b78-4f106bdd986e"
authors = ["Tommy Chu <chutommy@fit.cvut.cz>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
Flux = "0.16.0"
